### ISSUE TITLE
Background only extends until viewport height and TOC doesn't fold/unfold

### ISSUE THREAD

**Issue by NethumL** [fniessen/org-html-themes#143]
Expected: Background color of `#content` div should extend for the entire page, and TOC should fold/unfold when scrolling

Actual: Background of `#content` div only extends until viewport height, and TOC doesn't fold/unfold when scrolling 

![screenshot](https://user-images.githubusercontent.com/61122830/157449034-7ed188e5-b116-45e9-8fe3-e3a88080ef8b.png)

Minimal reproducible example (full example available [here](https://gist.github.com/NethumL/372c70b2410a5da33d78ecbc1cd430fa#file-z_test-org), this is just to show the most important parts):

``` org
#+TITLE: Test
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Heading 1
** Subheading 1.1
| a | b |
- Some filler content to make the page long enough to extend past the viewport (so that scrolling is required)
- Type of content doesn't seem to matter
** Subheading 1.2
- Some more filler content
```

In this, the table just under 'Subheading 1.1' is causing this (content of table doesn't matter). That may not be the only thing that can cause this, but removing it fixes the issue.

When this table is not present, the resulting HTML contains an additional DOCTYPE. Removing it causes the issue.

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
```

Adding it to the HTML generated while the table is in the org source file also fixes the issue.

This appears depending on the value of `org-html-doctype`. The default value, "xhtml-strict", causes this DOCTYPE to not be added when the table is present.

Changing it to "html5" fixes the issue. Either using a `(setq org-html-doctype "html5")` in the init.el, or by setting it per org file like `#+HTML_DOCTYPE: html5`

It's also possible to (fully) fix it by fixing this in the `readtheorg.css`

``` css
html{
    -ms-text-size-adjust:100%;
    -webkit-text-size-adjust:100%;
    font-size:100%;
    height:100%;
    overflow-x:hidden;   /* EITHER THIS LINE */
}

body{
    background:#edf0f2;
    color:#404040;
    font-family:"Lato","proxima-nova","Helvetica Neue",Arial,sans-serif;
    font-weight:normal;
    margin:0;
    min-height:100%;
    overflow-x:hidden;  /* OR THIS LINE MUST BE REMOVED */
}

#content{
    background:#fcfcfc;
    height:100%;  /* AND THIS LINE MUST BE REMOVED */
    margin-left:300px;
    /* margin:auto; */
    max-width:800px;
    min-height:100%;
    padding:1.618em 3.236em;
}
```

The `height:100%` in `#content` needs to be removed, and the `overflow-x:hidden` in *either* `html` or `body` has be removed

I've made these changes in a fork at [NethumL/org-html-themes](https://github.com/NethumL/org-html-themes/tree/fix-scroll) in the `fix-scroll` branch and it's hosted on [GitHub Pages](https://nethuml.github.io/org-html-themes/src/readtheorg_theme/css/readtheorg.css)
(I removed both `overflow-x` statements)

I've been using this forked version for a while, and so far, I have not found any other issues
