### ISSUE TITLE
readtheorg theme css interfering with MathJax rendering

### ISSUE THREAD

**Issue by er432** [fniessen/org-html-themes#86]
I noticed that use of the ReadtheOrg theme was causing the MathJax rendering to misbehave. That is, there was rendering of the equations, but the typesetting wound up misaligned. I managed to resolve this for myself by locally commenting out the following in the readtheorg.css file:
``` css
#content img{
    max-width:100%;
}
```
